import React from 'react'
import axios from 'axios'
import styles from '../../styles/Posts.module.css'
import Head from 'next/head'
import { useRouter } from 'next/router'

export const getStaticPaths = async() => {
    const res = await axios.get(`https://jsonplaceholder.typicode.com/posts`)
    const data = await res.data

    const paths = data.map(post => {
        return {
            params: {
                id: post.id.toString()
            }
        }
    })

    return {
        paths,
        fallback: false
    }
}

export const getStaticProps = async(context) => {
    const id = context.params.id
    const res = await axios.get(`https://jsonplaceholder.typicode.com/posts/${id}`)
    const data = await res.data

    return {
        props: { post: data }
    }
}

const SinglePost = ({ post }) => {
    const router = useRouter()

    return (
        <>
            <Head>
                <title>Post {post.id} - NextJS Tutorial</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.post}>
                <h3 className={styles.postTitle}>{post.title}</h3>
                <p>{post.body}</p>
                <button className={styles.btn} onClick={() => router.back()} type='button'>Volver</button>
            </div>
        </>
    )
}

export default SinglePost
