import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Image from 'next/image'
import image2 from '../public/images/image2.jpg'
import styles from '../styles/404.module.css'

const NotFound = () => {
    const router = useRouter()

    useEffect(() => {
        setTimeout(() => {
            router.push('/')
        }, 100000)
    }, [])

    return (
        <div>
        <Head>
            <title>Not Found - NextJS Tutorial</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <section>
            <h2>Página no encontrada</h2>
            <div className={styles.container}>
                <figure>
                    <Image priority src={image2} alt={image2} />
                </figure>
                <Link href='/'>Volver</Link>
            </div>
        </section>
        </div>
    )
}

export default NotFound
