import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
          <h2>Inicio</h2>
          <p>
            App hecha con NextJS
          </p>
      </section>
    </div>
  )
}
